### ISSUE TITLE
Restricted camera FOV - TrackIR 4 Pro - Mac OSX 10.10.2

### ISSUE THREAD

**Issue by iservin** [uglyDwarf/linuxtrack#109] opened 2016-01-16 17:53 UTC
I'm attempting to use a TrackIR 4 Pro w/ standard track clip on mac OSX Yosemite 10.10.2 with the latest 0.99.3 build.

Besides some stability issues, I'm running into a strange problem. It seems the TrackIR camera is only using half of its capture area. According to the camera display, tracking only works on a narrow band on the left side. I'm attaching a screenshot to help illustrate this problem, the red area is the only area that picks up anything.

<img width="880" alt="screen shot 2016-01-16 at 12 48 40 pm" src="https://cloud.githubusercontent.com/assets/1294186/12373705/0f926096-bc50-11e5-94ad-fe9b9d4432fd.png">

I have confirmed that the device is fully operational on a separate machine running windows 10. I am currently trying to update the firmware via linuxtrack but have been unable to download/extract the necessary files thus far.

**Comment by uglyDwarf** [comment] 2016-01-16 19:49
Hello,
the camera view looks wrong - there should be only black and white image of what the tracker sees. The red rectangle is definitely wrong...

Can you send me a log of your session? (Misc. pane, there is a button to package the logs).

Could you also elaborate a bit more on the stability issues you mentioned?

Kind regards,

Michal

**Comment by iservin** [comment] 2016-01-16 20:24
Apologies, I wasn't clear, I edited the screenshot to illustrate the area that appears to be picked up by the camera. The red rectangle was added in photoshop. It displays a normal camera feed in actuality, black background with properly identified tracking points, but only in that limited space. The camera feed and system in general works correctly in windows.

As far as stability is concerned, I'm unable to run the gui consistently. The first run or two works ok, then if I run it again sometimes the trackir won't start tracking at all, or if it does, the application will force quit after a couple minutes. Typically a restart is required to run it again.

I'm having issues with the logs, it's generating a lot of entries and copy/pasting and using the package log options aren't working. I managed to get a log that shows an instance of trying to start tracking and failing, the TrackIR's IR LEDs come on and the status LED turns green but the tracking hangs and the program will eventually force close. If this behavior happens with the GUI, it also appears in the X-plane plugin, keyboard/joystick shortcuts will appear to trigger start/stop of tracking according to the unit's status LED, but won't actually track. Again, a restart seems to solve this problem, at least temporarily.

[timeout_log.zip](https://github.com/uglyDwarf/linuxtrack/files/93071/timeout_log.zip)

I will restart now and attempt to get a log when the tracking is running. From memory, there was an error logged that said something about stripes and resolution.

**Comment by iservin** [comment] 2016-01-16 20:29
Ok, I managed to capture a log. This time the tracking froze up pretty quickly after restart but I see the error messages I noticed from before.

[stripe_log.zip](https://github.com/uglyDwarf/linuxtrack/files/93076/stripe_log.zip)

Just in case more info about my setup helps, here's a screenshot of my system overview.

<img width="282" alt="screen shot 2016-01-16 at 3 28 53 pm" src="https://cloud.githubusercontent.com/assets/1294186/12374320/edc21f4a-bc65-11e5-96a3-0c4ec93a6374.png">

**Comment by iservin** [comment] 2016-01-16 20:38
The stability is worsening. Even with a fresh copy of LinuxTrack and a restart I'm unable successfully run tracking for more than a minute or so. Not sure what's up here. Ran back to my Windows machine and it works as expected.

**Comment by iservin** [comment] 2016-01-16 21:17
Hmm, reinstalled firmware with extracted contents from NaturalPoint's latest release and the stability issues appear to be gone. Can stop/start tracking to my heart's content. Still have the stripes issue. I watched the logs while running tracking and every time a point goes out of frame, the stripe error message gets thrown. The x-plane plugin is running normally now as well save for the defacto limited FOV. As a temporary fix, I've placed the TrackIR unit as far away from me as possible and offset to my left by quite a bit. Not the best solution, but glad I can finally start to make use of your excellent work with linuxtrack.

Despite whatever issue I'm having, kudos for spending the time to fill in this gap, really boggles the mind why naturalpoint doesn't bother to do it themselves.

**Comment by iservin** [comment] 2016-01-16 21:41
Alas, I spoke too soon, got 30 minutes of use in before the timeout errors came back :(

**Comment by uglyDwarf** [comment] 2016-01-17 19:14
Hello,
as for the stability problems, I assume it has something with the image the camera sees; redownloading linuxtrack package won't make any difference (if the .dmg were corrupted, the system would catch it) and the firmware, as long as it is extracted OK, reinstalling it won't make any change (to the tracking process)...

Can you please look at Console application (in Applications/Utilities) and see if there aren't any crash dumps for Linuxtrack? Knowing where it goes bad would help me pinpointing the problem.

Will report back...

Kind regards,

Michal

**Comment by iservin** [comment] 2016-01-17 19:24
Opened the gui and reproduced the timeout error and subsequent ctd, here's the crashlog

[ltr_gui_crashlog.txt](https://github.com/uglyDwarf/linuxtrack/files/93572/ltr_gui_crashlog.txt)

**Comment by uglyDwarf** [comment] 2016-01-17 19:30
Hello,
there is something really wrong with 0.99.13 (unfortunately it didn't show up when I was testing it with TrackIR5) and I can reproduce at least a part of what you described...

Will report back as soon as I have something.

Kind regards,

Michal

**Comment by iservin** [comment] 2016-01-17 19:31
Phew, glad it's not just me. Thanks again for your work on this.

**Comment by uglyDwarf** [comment] 2016-01-17 20:40
Hello,
can you try this? http://linuxtrack.eu/repositories/universal/linuxtrack-0.99.13fix.dmg

Kind regards,

Michal

**Comment by iservin** [comment] 2016-01-19 02:21
Hey, sorry for the lack of comms.

It looks like that fix has cleared up the weird field of view issue/stripe error. Tracking works 100% as it should now, which is awesome. Unfortunately, I'm still getting the timeout error which leads to force closes in the gui and also when using the plugin in X-plane. I'll attach a crashlog of the most recent force close.
[linuxtrack_log_2.txt](https://github.com/uglyDwarf/linuxtrack/files/95235/linuxtrack_log_2.txt)

**Comment by uglyDwarf** [comment] 2016-01-19 06:16
No problem...

Just to make sure I understand what is going on; the timeout problems you mention - the tracking works for some time and then you get the timeouts and the tracking stops, right?

Just to have an idea what your setup looks like - do you have the TrackIR plugged directly to the USB port on the machine (is it USB2 or USB3?), or you use some hub (is it powered?) or extension cord?

I'll try to let the tracking run for some time and see if I can reproduce the problem you are seeing.

Kind regards,

Michal

**Comment by iservin** [comment] 2016-01-19 12:39
It's in one of the USB 3.0 ports on my retina macbook pro. 

Trying to think if anything about my setup is unusual. As far as any I/O I've got a second monitor hooked up via HDMI, a USB hub with mostly flight sim hardware and a keyboard, and a thunderbolt external hard drive dock. Other than that, pretty vanilla setup.

**Comment by uglyDwarf** [comment] 2016-01-19 19:15
Is the USB hub powered? Can you try attaching the TrackIR there and see if those timeouts go away?

The thing is, that TrackIR might have problems when plugged into USB3.0 ports ( http://help.naturalpoint.com/kb/articles/5-usb-3-0-issues )... Also El Capitan brought many changes and it seems they did something to the USB stack (some USB devices didn't work in earlier releases), so it is also a suspect... Thinking of it, El Capitan seems to be a bit higher on the list, since USB3.0 ports were on Macs probably since 2012 and such problems weren't reported on Yosemite and earlier... Or it might be a combination of both.

You do not have a way to run earlier MacOS X version on your machine, do you? If you do, could you try it to see if the problems are there too?

Thank you for your help,

Michal

**Comment by iservin** [comment] 2016-01-19 20:23
Didn't show up with my powered 2.0 hub but with an unpowered 2.0 hub it was better. Works more often, but still getting occasional FCs and timeout errors. It gets going, then if I stop/start a couple times it'll get unstable and it's 50/50 whether it'll work again without a restart after the crash. Before it was more like 90% likely to not work after crashing. I'll attach another crashlog from latest force close while it's plugged into the USB 2.0 unpowered hub.

I think I have access to an older iMac. I'm running Yosemite. Believe the older machine has Mountain Lion or Mavericks.

[linuxtrack_crashlog_3.txt](https://github.com/uglyDwarf/linuxtrack/files/96515/linuxtrack_crashlog_3.txt)

**Comment by uglyDwarf** [comment] 2016-01-19 20:51
OK, so you are on Yosemite (you wrote it in the first post, but I just forgotten)...

Can you try the older 0.99.12? (0.99.13 is necessary only on El Capitan) That version was out for about a year, without a problem (at least noone reported anything similar)...

The fact, that putting a hub in between changes the behavior is very good datapoint, thank you for giving it a try...

Kind regards,

Michal
PS. https://code.google.com/p/linux-track/wiki/Downloads?tm=2

**Comment by iservin** [comment] 2016-01-19 21:34
Alright, so bad news is I'm getting similar behavior in the GUI with 99.12.

Good news is that I've yet to have any trouble with actual use with the X-plane plugin. I've only done a couple flights, but had tracking on (with a few pauses) for over a half an hour with zero issues. I'll keep it running and see if it has any longevity issues, but I'm cautiously optimistic.

**Comment by iservin** [comment] 2016-01-23 16:26
Alright, so far no endurance issues with the plugin in X-plane. If I fiddle with the GUI I can still crash it, but I have to start/stop it a few times to make it upset. In real world usage all is good now. Thanks again for the help.

**Comment by uglyDwarf** [comment] 2016-01-23 19:29
Hello,
thanks for letting me know... Just to be sure - you are using the 0.99.12, right?

Strange thing is, that I don't see those GUI stability problems on Linux (which is my primary platform). On the other hand, I do see them in the El Capitan and it makes me wander why nobody reported them so far... Anyway, I'm trying to use valgrind to show me some problems - hopefully I'll be able to iron it out...

Thank you for your help,

Michal

**Comment by iservin** [comment] 2016-01-23 19:30
Yep, I'm using the 0.99.12 release.

**Comment by uglyDwarf** [comment] 2016-01-24 21:39
Hello,
I managed to find few problems and what I found should be fixed now...
Might I ask you to give it a shot? You can find it here: http://linuxtrack.eu/repositories/universal/linuxtrack-0.99.14.dmg

So far I didn't have a single crash since (if there is a problem left, maybe Murphy's laws will help it to show up)...

Kind regards,

Michal

**Comment by iservin** [comment] 2016-01-25 01:04
Nice. Haven't been able to trip it up yet. I'll let you know if I run into any issues but it's rock solid so far.

**Comment by uglyDwarf** [comment] 2016-01-25 19:22
Thank you for giving it a shot - I'll release the 0.99.14 then as it is a definitely a step forward...
Kind regards,

Michal

**Comment by uglyDwarf** [comment] 2016-01-28 19:52
Hello,
cleaning up a bit the issue backlog - I'm going to close this issue...
Should you encounter any other problems, please let me know.

Kind regards,

Michal

**Closed by uglyDwarf** 2016-01-28 19:52 UTC
